# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from NhuDanhDashboard import Ui_MainWindow

class Ui_Form(object):
    def setupUi(self, Form):
        self.Form = Form
        Form.setObjectName("Form")
        Form.resize(1025, 712)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 50, 801, 591))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(370, 100, 351, 361))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
                                 "")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 371, 371))
        self.label_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(0, 86, 79, 255));\n"
            "border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(470, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(470, 220, 180, 30))
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                    "border: 2px solid rgba(0, 0, 0, 0);\n"
                                    "border-bottom-color: rgba(46, 82, 101, 200);\n"
                                    "color: rgb(0, 0, 0);\n"
                                    "padding-bottom: 7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(470, 270, 180, 30))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
                                      "border: 2px solid rgba(0, 0, 0, 0);\n"
                                      "border-bottom-color: rgba(46, 82, 101, 200);\n"
                                      "color: rgb(0, 0, 0);\n"
                                      "padding-bottom: 7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton.setGeometry(QtCore.QRect(470, 340, 181, 31))
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
                                      "    background-color:rgba(0, 86, 79, 255);\n"
                                      "    color:rgba(255, 255, 255, 200);\n"
                                      "    border-radius: 5px;\n"
                                      "}    \n"
                                      "\n"
                                      "QPushButton#pushButton:pressed{\n"
                                      "\n"
                                      "    background-color: rgba(150, 86, 79, 255);\n"
                                      "    background-position: calc(100% - 10px)center;\n"
                                      "}    \n"
                                      "\n"
                                      "QPushButton#pushButton:hover{\n"
                                      "    background-color: rgba(150, 86, 79, 255);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(470, 400, 181, 31))
        self.exitButton.setStyleSheet("background-color: rgba(150, 0, 0, 255);\n"
                                      "color: rgba(255, 255, 255, 200);\n"
                                      "border-radius: 5px;")
        self.exitButton.setObjectName("exitButton")
        self.exitButton.setText("Exit")
        self.exitButton.clicked.connect(Form.close)
        self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.pushButton.clicked.connect(self.check_credentials)  # Connect login button to check credentials
        self.logo_label = QtWidgets.QLabel(self.widget)
        self.logo_label.setGeometry(QtCore.QRect(30, 70, 371, 371))  # Thay đổi kích thước và vị trí theo yêu cầu
        self.logo_label.setStyleSheet("border-radius: 10px;")
        pixmap = QtGui.QPixmap("nhudanhlog.jpg")  # Đảm bảo đường dẫn đúng
        if pixmap.isNull():
            print("Error: Logo image could not be loaded.")
        else:
            self.logo_label.setPixmap(pixmap)
        self.logo_label.setScaledContents(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.pushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Đăng nhập</p></body></html>"))
        self.lineEdit.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Tên đăng nhập"))
        self.lineEdit_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Mật khẩu"))
        self.pushButton.setText(_translate("Form", "Đăng nhập"))

    def check_credentials(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        # Replace this with your actual authentication logic
        if username == "admin" and password == "admin123":
            self.open_main_window()
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Invalid credentials")

    def open_main_window(self):
        self.main_window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_window)
        self.main_window.showMaximized()
        QtWidgets.QWidget().close()
        self.Form.close()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
